
package view;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.logging.LogManager;

import javax.swing.DefaultListModel;

import controller.ProjectsController;
import controller.TaskController;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import model.Projects;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author Alberto Araújo
 */
public class MainScreen extends javax.swing.JFrame {

        ProjectsController projectsController;
        TaskController taskController;

        DefaultListModel projectsModel;
        TaskTableModel taskModel;

        public MainScreen() {
                initComponents();
                initDataController();
                initComponentsModel();
                decorateTableTasks();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPaneTasks = new javax.swing.JScrollPane();
                jTableTasks = new javax.swing.JTable();
                jPanelEmptyList = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jListProject = new javax.swing.JList<>();
                jPanel5 = new javax.swing.JPanel();

                jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Nome", "Descrição", "Prazo", "Tarefa concluída"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.Boolean.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, true
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jTableTasks.setGridColor(java.awt.Color.white);
                jTableTasks.setRowHeight(40);
                jTableTasks.setSelectionBackground(new java.awt.Color(204, 255, 204));
                jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jTableTasks.setShowHorizontalLines(true);
                jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTableTasksMouseClicked(evt);
                        }
                });
                jScrollPaneTasks.setViewportView(jTableTasks);

                jPanelEmptyList.setBackground(java.awt.Color.white);

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

                jLabel8.setBackground(new java.awt.Color(0, 153, 102));
                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(0, 153, 102));
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("Nenhuma tarefa por aqui ;D");

                jLabel9.setBackground(new java.awt.Color(153, 153, 153));
                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel9.setText("Clique no botão + para adicionar uma nova tarefa");

                javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
                jPanelEmptyList.setLayout(jPanelEmptyListLayout);
                jPanelEmptyListLayout.setHorizontalGroup(
                                jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanelEmptyListLayout.createSequentialGroup()
                                                                                .addGroup(jPanelEmptyListLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel9,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                693,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel8,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel4,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addContainerGap()));
                jPanelEmptyListLayout.setVerticalGroup(
                                jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                                                                .addGap(104, 104, 104)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel9)
                                                                .addContainerGap(71, Short.MAX_VALUE)));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(800, 600));

                jPanel1.setBackground(new java.awt.Color(0, 153, 102));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
                jLabel1.setText(" Todo App");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Anote tudo não esqueça nada");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(12, 12, 12)));

                jPanel2.setBackground(java.awt.Color.white);
                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel3.setBackground(new java.awt.Color(0, 153, 102));
                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 153, 102));
                jLabel3.setText("Projetos");

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
                jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel6MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                112,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel3))
                                                                .addContainerGap()));

                jPanel3.setBackground(java.awt.Color.white);
                jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel5.setBackground(new java.awt.Color(0, 153, 102));
                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 153, 102));
                jLabel5.setText("Tarefas");

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel7MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5))
                                                                .addContainerGap()));

                jPanel4.setBackground(java.awt.Color.white);
                jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jListProject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jListProject.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jListProject.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jListProject.setFixedCellHeight(40);
                jListProject.setSelectionBackground(new java.awt.Color(0, 153, 102));
                jListProject.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jListProjectMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jListProject);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1)
                                                                .addContainerGap()));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1)
                                                                .addContainerGap()));

                jPanel5.setBackground(java.awt.Color.white);
                jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 711, Short.MAX_VALUE));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 439, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(14, 14, 14)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableTasksMouseClicked
                int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
                int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
                Task task = taskModel.getTasks().get(rowIndex);
                TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
                switch (columnIndex) {
                        case 3:
                                taskController.update(task);
                                break;
                        case 4:
                                taskDialogScreen.setTask(task);
                                taskDialogScreen.setFieldsName(task);
                                taskDialogScreen.setVisible(true);
                                taskDialogScreen.addWindowListener(new WindowAdapter() {
                                        public void windowClosed(WindowEvent e) {
                                                int projectIndex = jListProject.getSelectedIndex();
                                                Projects project = (Projects) projectsModel.get(projectIndex);
                                                loadTasks(project.getId());
                                        }
                                });
                                break;
                        case 5:
                                taskController.removeById(task.getId());
                                taskModel.getTasks().remove(task);
                                int projectIndex = jListProject.getSelectedIndex();
                                Projects project = (Projects) projectsModel.get(projectIndex);
                                loadTasks(project.getId());
                                break;
                        default:
                                break;

                }
        }// GEN-LAST:event_jTableTasksMouseClicked

        private void jListProjectMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jListProjectMouseClicked
                int projectIndex = jListProject.getSelectedIndex();
                Projects project = (Projects) projectsModel.get(projectIndex);
                taskModel = new TaskTableModel();
                jTableTasks.setModel(taskModel);
                loadTasks(project.getId());
        }// GEN-LAST:event_jListProjectMouseClicked

        private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel7MouseClicked
                TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
                int projectIndex = jListProject.getSelectedIndex();
                Projects project = (Projects) projectsModel.get(projectIndex);
                taskDialogScreen.setProject(project);
                taskDialogScreen.setVisible(true);
                taskDialogScreen.addWindowListener(new WindowAdapter() {
                        public void windowClosed(WindowEvent e) {
                                int projectIndex = jListProject.getSelectedIndex();
                                Projects project = (Projects) projectsModel.get(projectIndex);
                                loadTasks(project.getId());
                        }
                });
        }// GEN-LAST:event_jLabel7MouseClicked

        private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked
                ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
                projectDialogScreen.setVisible(true);
                projectDialogScreen.addWindowListener(new WindowAdapter() {
                        ;
                        public void windowClosed(WindowEvent e) {
                                loadProjects();
                        }
                });
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Java swing".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainScreen().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JList<String> jListProject;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanelEmptyList;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPaneTasks;
        private javax.swing.JTable jTableTasks;
        // End of variables declaration//GEN-END:variables

        public void decorateTableTasks() {
                jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
                jTableTasks.getTableHeader().setBackground(new Color(0, 153, 102));
                jTableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
                jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
                jTableTasks.setAutoCreateRowSorter(true);
                jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
                jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
        }

        public void initDataController() {
                projectsController = new ProjectsController();
                taskController = new TaskController();
        }

        public void initComponentsModel() {
                projectsModel = new DefaultListModel();
                loadProjects();
                taskModel = new TaskTableModel();
                jTableTasks.setModel(taskModel);
                if (!projectsModel.isEmpty()) {
                        jListProject.setSelectedIndex(0);
                        Projects project = (Projects) projectsModel.get(0);
                        loadTasks(project.getId());
                }
        }

        public void loadProjects() {
                List<Projects> projects = projectsController.getAll();
                projectsModel.clear();
                for (int i = 0; i < projects.size(); i++) {
                        Projects project = projects.get(i);
                        projectsModel.addElement(project);
                }
                jListProject.setModel(projectsModel);
        }

        public void showJTableTasks(boolean hasTasks) {
                if (hasTasks) {
                        if (jPanelEmptyList.isVisible()) {
                                jPanelEmptyList.setVisible(false);
                                jPanel5.remove(jPanelEmptyList);
                        }
                        jPanel5.remove(jScrollPaneTasks);
                        jPanel5.add(jScrollPaneTasks);
                        jScrollPaneTasks.setVisible(true);
                        jScrollPaneTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
                } else {
                        if (jScrollPaneTasks.isVisible()) {
                                jScrollPaneTasks.setVisible(false);
                                jPanel5.remove(jScrollPaneTasks);
                        }
                        jPanel5.add(jPanelEmptyList);
                        jPanelEmptyList.setVisible(true);
                        jPanelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
                }
        };

        public void loadTasks(int idProject) {
                List<Task> tasks = taskController.getAll(idProject);
                taskModel.setTasks(tasks);
                showJTableTasks(!tasks.isEmpty());
        };
}
