/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Projects;
import model.Task;

/**
 *
 * @author alber
 */
public class TaskDialogScreen extends javax.swing.JDialog {

        TaskController controller;
        Projects project;

        public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                controller = new TaskController();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelToolBar = new javax.swing.JPanel();
                jLabelToolBarTitle = new javax.swing.JLabel();
                jLabelToolBarSave = new javax.swing.JLabel();
                jPanelTask = new javax.swing.JPanel();
                jLabelName = new javax.swing.JLabel();
                jTextFieldName = new javax.swing.JTextField();
                jLabelDescription = new javax.swing.JLabel();
                jTextFieldDescription = new javax.swing.JTextField();
                jLabelDeadline = new javax.swing.JLabel();
                jFormattedTextFieldDeadline = new javax.swing.JFormattedTextField();
                jLabelNotes = new javax.swing.JLabel();
                jTextFieldNotes = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

                jLabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabelToolBarTitle.setForeground(java.awt.Color.white);
                jLabelToolBarTitle.setText("Tarefas");

                jLabelToolBarSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelToolBarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
                jLabelToolBarSave.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelToolBarSaveMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
                jPanelToolBar.setLayout(jPanelToolBarLayout);
                jPanelToolBarLayout.setHorizontalGroup(
                                jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelToolBarLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabelToolBarTitle,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                371,
                                                                                Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabelToolBarSave,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(15, 15, 15)));
                jPanelToolBarLayout.setVerticalGroup(
                                jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanelToolBarLayout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabelToolBarSave,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                88,
                                                                                                Short.MAX_VALUE)
                                                                                .addContainerGap())
                                                .addComponent(jLabelToolBarTitle,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));

                jPanelTask.setBackground(java.awt.Color.white);

                jLabelName.setBackground(java.awt.Color.white);
                jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelName.setText("Nome");

                jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabelDescription.setBackground(java.awt.Color.white);
                jLabelDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelDescription.setText("Descrição");

                jTextFieldDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextFieldDescription.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDescriptionActionPerformed(evt);
                        }
                });

                jLabelDeadline.setBackground(java.awt.Color.white);
                jLabelDeadline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelDeadline.setText("Prazo");

                jFormattedTextFieldDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.DateFormatter(
                                                java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

                jLabelNotes.setBackground(java.awt.Color.white);
                jLabelNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelNotes.setText("Notas");

                jTextFieldNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                javax.swing.GroupLayout jPanelTaskLayout = new javax.swing.GroupLayout(jPanelTask);
                jPanelTask.setLayout(jPanelTaskLayout);
                jPanelTaskLayout.setHorizontalGroup(
                                jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelTaskLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(
                                                                                jPanelTaskLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jTextFieldName,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                420,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabelName,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jTextFieldDescription)
                                                                                                .addComponent(jLabelDescription,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabelDeadline,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jTextFieldNotes)
                                                                                                .addComponent(jLabelNotes,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jFormattedTextFieldDeadline))
                                                                .addContainerGap()));
                jPanelTaskLayout.setVerticalGroup(
                                jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelTaskLayout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(jLabelName)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDescription)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldDescription,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                120,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabelDeadline)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jFormattedTextFieldDeadline,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelNotes)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldNotes,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                120,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanelTask,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanelToolBar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanelTask,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTextFieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldDescriptionActionPerformed
        }// GEN-LAST:event_jTextFieldDescriptionActionPerformed

        private void jLabelToolBarSaveMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelToolBarSaveMouseClicked
                try {
                        if (!jTextFieldName.getText().isEmpty()
                                        && !jFormattedTextFieldDeadline.getText().isEmpty()) {
                                Task task = new Task();
                                task.setIdProject(project.getId());
                                task.setName(jTextFieldName.getText());
                                task.setDescription(jTextFieldDescription.getText());
                                task.setNotes(jTextFieldNotes.getText());
                                task.setCompleted(false);
                                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                                Date deadline = null;
                                deadline = dateFormat.parse(jFormattedTextFieldDeadline.getText());
                                task.setDeadline(deadline);
                                controller.save(task);
                                JOptionPane.showMessageDialog(rootPane, "Tarefa incluída com sucesso");
                                this.dispose();
                        } else {
                                JOptionPane.showMessageDialog(rootPane, "A tarefa não foi salva"
                                                + "pois existem campos obrigatórios a serem preenchidos");
                        }
                } catch (Exception error) {
                        JOptionPane.showMessageDialog(rootPane, error);
                }
        }// GEN-LAST:event_jLabelToolBarSaveMouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFormattedTextField jFormattedTextFieldDeadline;
        private javax.swing.JLabel jLabelDeadline;
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelName;
        private javax.swing.JLabel jLabelNotes;
        private javax.swing.JLabel jLabelToolBarSave;
        private javax.swing.JLabel jLabelToolBarTitle;
        private javax.swing.JPanel jPanelTask;
        private javax.swing.JPanel jPanelToolBar;
        private javax.swing.JTextField jTextFieldDescription;
        private javax.swing.JTextField jTextFieldName;
        private javax.swing.JTextField jTextFieldNotes;
        // End of variables declaration//GEN-END:variables

        public void setProject(Projects project) {
                this.project = project;
        }

}
